"""db update

Revision ID: a277fca337dc
Revises: 
Create Date: 2024-01-25 14:53:40.873837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a277fca337dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users')),
    sa.UniqueConstraint('username', name=op.f('uq_Users_username'))
    )
    op.create_table('Workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Workouts'))
    )
    op.create_table('Sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Sets_user_id_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Sets'))
    )
    op.create_table('Set_Workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['Sets.id'], name=op.f('fk_Set_Workouts_set_id_Sets')),
    sa.ForeignKeyConstraint(['workout_id'], ['Workouts.id'], name=op.f('fk_Set_Workouts_workout_id_Workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Set_Workouts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Set_Workouts')
    op.drop_table('Sets')
    op.drop_table('Workouts')
    op.drop_table('Users')
    # ### end Alembic commands ###
